apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: anomaly-detector
  namespace: dev
spec:
  replicas: 1
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: { duration: 30s }
      - setWeight: 100
  selector:
    matchLabels:
      app: anomaly-detector
  template:
    metadata:
      labels:
        app: anomaly-detector
    spec:
      serviceAccountName: anomaly-detector-ksa
      containers:
      - name: detector
        image: vinaygolkonda99/anomaly-detector:latest
        env:
        - name: GCS_BUCKET
          value: "anomaly-detector-logs"
        volumeMounts:
        - name: input-logs
          mountPath: /logs/input
          readOnly: true
        - name: output-logs
          mountPath: /logs/output
      volumes:
      - name: input-logs
        configMap:
          name: anomaly-logs
      - name: output-logs
        emptyDir: {}
